#!/usr/bin/env ruby

pwd = `pwd`.chomp

def copy_config(from,to)
	`rm #{to}` if File.exists?("#{to}.bak")
	`mv #{to} #{to}.bak`
	`ln -s #{from} #{to}`
end

copy_config("#{pwd}/mythtv","~/.mythtv/lircrc")
copy_config("#{pwd}/irexec","~/.lirc/irexec")


`mkdir ~/bin` unless File.exists?("~/bin")
`ln -s #{pwd}/*sh ~/bin`

%w[irda-utils xmacro].each do|pkg|
	puts "install #{pkg}..."
	`sudo apt-get install #{pkg}`
end

