#!/usr/bin/env ruby

def copy_config(from,to)
	`rm #{to}` if File.exists?("#{to}.bak")
	`mv #{to} #{to}.bak`
	`ln -s #{from} #{to}`
end

def install_pkgs(pkgs)
	pkgs.each do|pkg|
		puts "\tinstall #{pkg}..."
		`sudo apt-get install --assume-yes #{pkg}`
	end
end

puts "Installing useful packages"
install_pkgs(%w[xclip gkrellm htop screen vim zsh apt-file aptitude fsarchiver gparted])

puts "Do you want to install the Remote Control?"
if gets =~ /[Yy]/

	puts "Installing Remote Control"
	pwd = `pwd`.chomp

	copy_config("#{pwd}/mythtv","~/.mythtv/lircrc")
	copy_config("#{pwd}/irexec","~/.lirc/irexec")

	`mkdir ~/bin` unless File.exists?("~/bin")
	`ln -s #{pwd}/*sh ~/bin`

	install_pkgs(%w[irda-utils xmacro])

	# Restart lirc
	`sudo service lirc restart`
end

puts "\nDo you want to install the Shepherd?"
if gets =~ /[Yy]/
	puts "\nInstalling Shepherd"

	install_pkgs(%w[xmltv libxml-simple-perl libalgorithm-diff-perl libgetopt-mixed-perl libcompress-zlib-perl libdata-dumper-simple-perl libdate-manip-perl liblist-compare-perl libdatetime-format-strptime-perl libhtml-parser-perl libxml-dom-perl libgd-gd2-perl libdigest-sha1-perl libarchive-zip-perl libio-string-perl libdbi-perl])

	`wget http://www.whuffy.com/shepherd/shepherd`
	puts "\nAfter you have scanned and setup TV stations run perl shepherd"
end



