#!/usr/bin/env ruby
#
# backup-chroot-script
#
# This can be used on any LTSP machine to backup the client image to a bakcup
# location
#
# Required
#  - pbzip2
#

puts "Make sure you run this with root access"

backup_dir = "i386"

Dir.chdir("/opt/ltsp")

date = Time.now.strftime("%Y%m%d-%H%M")
filename="#{date}-i386.tar.gz"
name = "/storage1/backup/chroot/#{filename}"

if File.exists?(name)
	puts "\nBackup file #{name} already exists, \nplease remove before running this backup script again.\n\n"
	exit
end

puts "Backup #{backup_dir} to #{name}..."
puts "Hit enter to continue"
gets

puts "Enter comment"
comment = filename + " = " + gets.chomp

puts "\n\nBacking up please wait....\n\n"
`tar --use-compress-prog=pbzip2 -cf #{name} #{backup_dir}`

`echo "#{comment}" >> readme.txt`

